### ISSUE TITLE
Fails to build on 32-bit architectures (e.g., armv7, i386, powerpc)

### ISSUE THREAD

**Issue by jbeich** [hyprwm/hyprpaper#139]
Regressed by 39ad021c7599. See also https://github.com/hyprwm/hyprlang/issues/8

```c++
$ export CXXFLAGS=-m32
$ cmake -G Ninja -B /tmp/hyprpaper_build
$ cmake --build /tmp/hyprpaper_build 
[...]
src/config/ConfigManager.cpp:135:35: error: call to constructor of 'const Hyprlang::CConfigValue &' is ambiguous
    config->addConfigValue("ipc", {1L});
                                  ^~~~
/usr/include/hyprlang.hpp:192:9: note: candidate constructor
        CConfigValue(const INT value);
        ^
/usr/include/hyprlang.hpp:193:9: note: candidate constructor
        CConfigValue(const FLOAT value);
        ^
/usr/include/hyprlang.hpp:289:67: note: passing argument to parameter 'value' here
        void addConfigValue(const char* name, const CConfigValue& value);
                                                                  ^
src/config/ConfigManager.cpp:136:38: error: call to constructor of 'const Hyprlang::CConfigValue &' is ambiguous
    config->addConfigValue("splash", {0L});
                                     ^~~~
/usr/include/hyprlang.hpp:192:9: note: candidate constructor
        CConfigValue(const INT value);
        ^
/usr/include/hyprlang.hpp:193:9: note: candidate constructor
        CConfigValue(const FLOAT value);
        ^
/usr/include/hyprlang.hpp:194:9: note: candidate constructor
        CConfigValue(const STRING value);
        ^
/usr/include/hyprlang.hpp:289:67: note: passing argument to parameter 'value' here
        void addConfigValue(const char* name, const CConfigValue& value);
                                                                  ^
2 errors generated.
```

**Comment by vaxerski** [comment]
should be done with above
