### ISSUE TITLE
Fails to build with hyprwayland-scanner >= 0.4.3

### ISSUE THREAD

**Issue by jbeich** [hyprwm/hyprpaper#230]
505e447b6c48 is probably not enough:
```c++
protocols/wayland.cpp:70:58: error: unknown type name 'wl_resource'
   70 | static void _CWlDisplayError(void* data, void* resource, wl_resource* object_id, uint32_t code, const char* message) {
      |                                                          ^
protocols/wayland.cpp:135:26: error: unknown type name 'wl_resource'
  135 | CCWlDisplay::CCWlDisplay(wl_resource* resource) {
      |                          ^
protocols/wayland.cpp:149:49: error: unknown type name 'wl_resource'
  149 | void CCWlDisplay::setError(F<void(CCWlDisplay*, wl_resource*, uint32_t, const char*)> handler) {
      |                                                 ^
protocols/wayland.cpp:149:19: error: out-of-line definition of 'setError' does not match any declaration in 'CCWlDisplay'
  149 | void CCWlDisplay::setError(F<void(CCWlDisplay*, wl_resource*, uint32_t, const char*)> handler) {
      |                   ^~~~~~~~
protocols/wayland.hpp:172:19: note: type of 1st parameter of member declaration does not match definition ('function<void (CCWlDisplay *, wl_proxy *, uint32_t, const char *)>' vs 'function<void (CCWlDisplay *, int *, uint32_t, const char *)>')
  172 |     void setError(F<void(CCWlDisplay*, wl_resource*, uint32_t, const char*)> handler);
      |                   ^
protocols/wayland.hpp:42:11: note: expanded from macro 'F'
   42 | #define F std::function
      |           ^
protocols/wayland.cpp:150:20: error: no viable overloaded '='
  150 |     requests.error = handler;
      |     ~~~~~~~~~~~~~~ ^ ~~~~~~~
/usr/include/c++/v1/__functional/function.h:875:35: note: candidate function not viable: no known conversion from 'function<void (CCWlDisplay *, int *, uint32_t, const char *)>' to 'const function<void (CCWlDisplay *, wl_proxy *, unsigned int, const char *)>' for 1st argument
  875 |   _LIBCPP_HIDE_FROM_ABI function& operator=(const function&);
      |                                   ^         ~~~~~~~~~~~~~~~
/usr/include/c++/v1/__functional/function.h:876:35: note: candidate function not viable: no known conversion from 'function<void (CCWlDisplay *, int *, uint32_t, const char *)>' to 'function<void (CCWlDisplay *, wl_proxy *, unsigned int, const char *)>' for 1st argument
  876 |   _LIBCPP_HIDE_FROM_ABI function& operator=(function&&) _NOEXCEPT;
      |                                   ^         ~~~~~~~~~~
/usr/include/c++/v1/__functional/function.h:877:35: note: candidate function not viable: no known conversion from 'std::function<void (CCWlDisplay *, int *, uint32_t, const char *)>' (aka 'function<void (CCWlDisplay *, int *, unsigned int, const char *)>') to 'nullptr_t' (aka 'std::nullptr_t') for 1st argument
  877 |   _LIBCPP_HIDE_FROM_ABI function& operator=(nullptr_t) _NOEXCEPT;
      |                                   ^         ~~~~~~~~~
/usr/include/c++/v1/__functional/function.h:879:35: note: candidate template ignored: requirement '__callable<std::function<void (CCWlDisplay *, int *, unsigned int, const char *)> &, false>::value' was not satisfied [with _Fp = std::function<void (CCWlDisplay *, int *, uint32_t, const char *)> &]
  879 |   _LIBCPP_HIDE_FROM_ABI function& operator=(_Fp&&);
      |                                   ^
protocols/wayland.cpp:209:28: error: unknown type name 'wl_resource'
  209 | CCWlRegistry::CCWlRegistry(wl_resource* resource) {
      |                            ^
protocols/wayland.cpp:254:28: error: unknown type name 'wl_resource'
  254 | CCWlCallback::CCWlCallback(wl_resource* resource) {
      |                            ^
protocols/wayland.cpp:310:32: error: unknown type name 'wl_resource'
  310 | CCWlCompositor::CCWlCompositor(wl_resource* resource) {
      |                                ^
protocols/wayland.cpp:376:26: error: unknown type name 'wl_resource'
  376 | CCWlShmPool::CCWlShmPool(wl_resource* resource) {
      |                          ^
protocols/wayland.cpp:441:18: error: unknown type name 'wl_resource'
  441 | CCWlShm::CCWlShm(wl_resource* resource) {
      |                  ^
protocols/wayland.cpp:492:24: error: unknown type name 'wl_resource'
  492 | CCWlBuffer::CCWlBuffer(wl_resource* resource) {
      |                        ^
protocols/wayland.cpp:616:30: error: unknown type name 'wl_resource'
  616 | CCWlDataOffer::CCWlDataOffer(wl_resource* resource) {
      |                              ^
protocols/wayland.cpp:749:32: error: unknown type name 'wl_resource'
  749 | CCWlDataSource::CCWlDataSource(wl_resource* resource) {
      |                                ^
protocols/wayland.cpp:793:78: error: unknown type name 'wl_resource'
  793 | static void _CWlDataDeviceEnter(void* data, void* resource, uint32_t serial, wl_resource* surface, wl_fixed_t x, wl_fixed_t y, wl_resource* id) {
      |                                                                              ^
protocols/wayland.cpp:793:128: error: unknown type name 'wl_resource'
  793 | static void _CWlDataDeviceEnter(void* data, void* resource, uint32_t serial, wl_resource* surface, wl_fixed_t x, wl_fixed_t y, wl_resource* id) {
      |                                                                                                                                ^
protocols/wayland.cpp:817:65: error: unknown type name 'wl_resource'
  817 | static void _CWlDataDeviceSelection(void* data, void* resource, wl_resource* id) {
      |                                                                 ^
protocols/wayland.cpp:906:32: error: unknown type name 'wl_resource'
  906 | CCWlDataDevice::CCWlDataDevice(wl_resource* resource) {
      |                                ^
protocols/wayland.cpp:924:65: error: unknown type name 'wl_resource'
  924 | void CCWlDataDevice::setEnter(F<void(CCWlDataDevice*, uint32_t, wl_resource*, wl_fixed_t, wl_fixed_t, wl_resource*)> handler) {
      |                                                                 ^
protocols/wayland.cpp:924:103: error: unknown type name 'wl_resource'
  924 | void CCWlDataDevice::setEnter(F<void(CCWlDataDevice*, uint32_t, wl_resource*, wl_fixed_t, wl_fixed_t, wl_resource*)> handler) {
      |                                                                                                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
protocols/wlr-layer-shell-unstable-v1.cpp:54:51: error: unknown type name 'wl_resource'
   54 | wl_proxy* CCZwlrLayerShellV1::sendGetLayerSurface(wl_resource* surface, wl_resource* output, zwlrLayerShellV1Layer layer, const char* namespace_) {
      |                                                   ^
protocols/wlr-layer-shell-unstable-v1.cpp:54:73: error: unknown type name 'wl_resource'
   54 | wl_proxy* CCZwlrLayerShellV1::sendGetLayerSurface(wl_resource* surface, wl_resource* output, zwlrLayerShellV1Layer layer, const char* namespace_) {
      |                                                                         ^
protocols/wlr-layer-shell-unstable-v1.cpp:80:40: error: unknown type name 'wl_resource'
   80 | CCZwlrLayerShellV1::CCZwlrLayerShellV1(wl_resource* resource) {
      |                                        ^
protocols/wlr-layer-shell-unstable-v1.cpp:151:41: error: unknown type name 'wl_resource'
  151 | void CCZwlrLayerSurfaceV1::sendGetPopup(wl_resource* popup) {
      |                                         ^
protocols/wlr-layer-shell-unstable-v1.cpp:228:44: error: unknown type name 'wl_resource'
  228 | CCZwlrLayerSurfaceV1::CCZwlrLayerSurfaceV1(wl_resource* resource) {
      |                                            ^
5 errors generated.
protocols/linux-dmabuf-v1.cpp:93:54: error: unknown type name 'wl_resource'
   93 | wl_proxy* CCZwpLinuxDmabufV1::sendGetSurfaceFeedback(wl_resource* surface) {
      |                                                      ^
protocols/linux-dmabuf-v1.cpp:138:40: error: unknown type name 'wl_resource'
  138 | CCZwpLinuxDmabufV1::CCZwpLinuxDmabufV1(wl_resource* resource) {
      |                                        ^
protocols/linux-dmabuf-v1.cpp:253:52: error: unknown type name 'wl_resource'
  253 | CCZwpLinuxBufferParamsV1::CCZwpLinuxBufferParamsV1(wl_resource* resource) {
      |                                                    ^
protocols/linux-dmabuf-v1.cpp:372:56: error: unknown type name 'wl_resource'
  372 | CCZwpLinuxDmabufFeedbackV1::CCZwpLinuxDmabufFeedbackV1(wl_resource* resource) {
      |                                                        ^
4 errors generated.
protocols/fractional-scale-v1.cpp:59:64: error: unknown type name 'wl_resource'
   59 | wl_proxy* CCWpFractionalScaleManagerV1::sendGetFractionalScale(wl_resource* surface) {
      |                                                                ^
protocols/fractional-scale-v1.cpp:83:60: error: unknown type name 'wl_resource'
   83 | CCWpFractionalScaleManagerV1::CCWpFractionalScaleManagerV1(wl_resource* resource) {
      |                                                            ^
protocols/fractional-scale-v1.cpp:133:46: error: unknown type name 'wl_resource'
  133 | CCWpFractionalScaleV1::CCWpFractionalScaleV1(wl_resource* resource) {
      |                                              ^
3 errors generated.
protocols/viewporter.cpp:59:43: error: unknown type name 'wl_resource'
   59 | wl_proxy* CCWpViewporter::sendGetViewport(wl_resource* surface) {
      |                                           ^
protocols/viewporter.cpp:83:32: error: unknown type name 'wl_resource'
   83 | CCWpViewporter::CCWpViewporter(wl_resource* resource) {
      |                                ^
protocols/viewporter.cpp:147:28: error: unknown type name 'wl_resource'
  147 | CCWpViewport::CCWpViewport(wl_resource* resource) {
      |                            ^
3 errors generated.
protocols/xdg-shell.cpp:85:42: error: unknown type name 'wl_resource'
   85 | wl_proxy* CCXdgWmBase::sendGetXdgSurface(wl_resource* surface) {
      |                                          ^
protocols/xdg-shell.cpp:132:26: error: unknown type name 'wl_resource'
  132 | CCXdgWmBase::CCXdgWmBase(wl_resource* resource) {
      |                          ^
protocols/xdg-shell.cpp:283:34: error: unknown type name 'wl_resource'
  283 | CCXdgPositioner::CCXdgPositioner(wl_resource* resource) {
      |                                  ^
protocols/xdg-shell.cpp:388:28: error: unknown type name 'wl_resource'
  388 | CCXdgSurface::CCXdgSurface(wl_resource* resource) {
      |                            ^
protocols/xdg-shell.cpp:470:40: error: unknown type name 'wl_resource'
  470 | void CCXdgToplevel::sendShowWindowMenu(wl_resource* seat, uint32_t serial, int32_t x, int32_t y) {
      |                                        ^
protocols/xdg-shell.cpp:478:30: error: unknown type name 'wl_resource'
  478 | void CCXdgToplevel::sendMove(wl_resource* seat, uint32_t serial) {
      |                              ^
protocols/xdg-shell.cpp:486:32: error: unknown type name 'wl_resource'
  486 | void CCXdgToplevel::sendResize(wl_resource* seat, uint32_t serial, xdgToplevelResizeEdge edges) {
      |                                ^
protocols/xdg-shell.cpp:526:39: error: unknown type name 'wl_resource'
  526 | void CCXdgToplevel::sendSetFullscreen(wl_resource* output) {
      |                                       ^
protocols/xdg-shell.cpp:627:30: error: unknown type name 'wl_resource'
  627 | CCXdgToplevel::CCXdgToplevel(wl_resource* resource) {
      |                              ^
protocols/xdg-shell.cpp:690:27: error: unknown type name 'wl_resource'
  690 | void CCXdgPopup::sendGrab(wl_resource* seat, uint32_t serial) {
      |                           ^
protocols/xdg-shell.cpp:741:24: error: unknown type name 'wl_resource'
  741 | CCXdgPopup::CCXdgPopup(wl_resource* resource) {
      |                        ^
11 errors generated.
protocols/cursor-shape-v1.cpp:59:52: error: unknown type name 'wl_resource'
   59 | wl_proxy* CCWpCursorShapeManagerV1::sendGetPointer(wl_resource* pointer) {
      |                                                    ^
protocols/cursor-shape-v1.cpp:68:57: error: unknown type name 'wl_resource'
   68 | wl_proxy* CCWpCursorShapeManagerV1::sendGetTabletToolV2(wl_resource* tablet_tool) {
      |                                                         ^
protocols/cursor-shape-v1.cpp:97:52: error: unknown type name 'wl_resource'
   97 | CCWpCursorShapeManagerV1::CCWpCursorShapeManagerV1(wl_resource* resource) {
      |                                                    ^
protocols/cursor-shape-v1.cpp:146:50: error: unknown type name 'wl_resource'
  146 | CCWpCursorShapeDeviceV1::CCWpCursorShapeDeviceV1(wl_resource* resource) {
      |                                                  ^
4 errors generated.
protocols/tablet-v2.cpp:60:51: error: unknown type name 'wl_resource'
   60 | wl_proxy* CCZwpTabletManagerV2::sendGetTabletSeat(wl_resource* seat) {
      |                                                   ^
protocols/tablet-v2.cpp:93:44: error: unknown type name 'wl_resource'
   93 | CCZwpTabletManagerV2::CCZwpTabletManagerV2(wl_resource* resource) {
      |                                            ^
protocols/tablet-v2.cpp:165:38: error: unknown type name 'wl_resource'
  165 | CCZwpTabletSeatV2::CCZwpTabletSeatV2(wl_resource* resource) {
      |                                      ^
protocols/tablet-v2.cpp:227:87: error: unknown type name 'wl_resource'
  227 | static void _CZwpTabletToolV2ProximityIn(void* data, void* resource, uint32_t serial, wl_resource* tablet, wl_resource* surface) {
      |                                                                                       ^
protocols/tablet-v2.cpp:227:108: error: unknown type name 'wl_resource'
  227 | static void _CZwpTabletToolV2ProximityIn(void* data, void* resource, uint32_t serial, wl_resource* tablet, wl_resource* surface) {
      |                                                                                                            ^
protocols/tablet-v2.cpp:327:56: error: unknown type name 'wl_resource'
  327 | void CCZwpTabletToolV2::sendSetCursor(uint32_t serial, wl_resource* surface, int32_t hotspot_x, int32_t hotspot_y) {
      |                                                        ^
protocols/tablet-v2.cpp:437:38: error: unknown type name 'wl_resource'
  437 | CCZwpTabletToolV2::CCZwpTabletToolV2(wl_resource* resource) {
      |                                      ^
protocols/tablet-v2.cpp:475:77: error: unknown type name 'wl_resource'
  475 | void CCZwpTabletToolV2::setProximityIn(F<void(CCZwpTabletToolV2*, uint32_t, wl_resource*, wl_resource*)> handler) {
      |                                                                             ^
protocols/tablet-v2.cpp:475:91: error: unknown type name 'wl_resource'
  475 | void CCZwpTabletToolV2::setProximityIn(F<void(CCZwpTabletToolV2*, uint32_t, wl_resource*, wl_resource*)> handler) {
      |                                                                                           ^
protocols/tablet-v2.cpp:475:25: error: out-of-line definition of 'setProximityIn' does not match any declaration in 'CCZwpTabletToolV2'
  475 | void CCZwpTabletToolV2::setProximityIn(F<void(CCZwpTabletToolV2*, uint32_t, wl_resource*, wl_resource*)> handler) {
      |                         ^~~~~~~~~~~~~~
protocols/tablet-v2.hpp:258:25: note: type of 1st parameter of member declaration does not match definition ('function<void (CCZwpTabletToolV2 *, uint32_t, wl_proxy *, wl_proxy *)>' vs 'function<void (CCZwpTabletToolV2 *, uint32_t, int *, int *)>')
  258 |     void setProximityIn(F<void(CCZwpTabletToolV2*, uint32_t, wl_resource*, wl_resource*)> handler);
      |                         ^
protocols/tablet-v2.hpp:41:11: note: expanded from macro 'F'
   41 | #define F std::function
      |           ^
protocols/tablet-v2.cpp:476:26: error: no viable overloaded '='
  476 |     requests.proximityIn = handler;
      |     ~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~
/usr/include/c++/v1/__functional/function.h:875:35: note: candidate function not viable: no known conversion from 'function<void (CCZwpTabletToolV2 *, uint32_t, int *, int *)>' to 'const function<void (CCZwpTabletToolV2 *, unsigned int, wl_proxy *, wl_proxy *)>' for 1st argument
  875 |   _LIBCPP_HIDE_FROM_ABI function& operator=(const function&);
      |                                   ^         ~~~~~~~~~~~~~~~
/usr/include/c++/v1/__functional/function.h:876:35: note: candidate function not viable: no known conversion from 'function<void (CCZwpTabletToolV2 *, uint32_t, int *, int *)>' to 'function<void (CCZwpTabletToolV2 *, unsigned int, wl_proxy *, wl_proxy *)>' for 1st argument
  876 |   _LIBCPP_HIDE_FROM_ABI function& operator=(function&&) _NOEXCEPT;
      |                                   ^         ~~~~~~~~~~
/usr/include/c++/v1/__functional/function.h:877:35: note: candidate function not viable: no known conversion from 'std::function<void (CCZwpTabletToolV2 *, uint32_t, int *, int *)>' (aka 'function<void (CCZwpTabletToolV2 *, unsigned int, int *, int *)>') to 'nullptr_t' (aka 'std::nullptr_t') for 1st argument
  877 |   _LIBCPP_HIDE_FROM_ABI function& operator=(nullptr_t) _NOEXCEPT;
      |                                   ^         ~~~~~~~~~
/usr/include/c++/v1/__functional/function.h:879:35: note: candidate template ignored: requirement '__callable<std::function<void (CCZwpTabletToolV2 *, unsigned int, int *, int *)> &, false>::value' was not satisfied [with _Fp = std::function<void (CCZwpTabletToolV2 *, uint32_t, int *, int *)> &]
  879 |   _LIBCPP_HIDE_FROM_ABI function& operator=(_Fp&&);
      |                                   ^
protocols/tablet-v2.cpp:602:30: error: unknown type name 'wl_resource'
  602 | CCZwpTabletV2::CCZwpTabletV2(wl_resource* resource) {
      |                              ^
protocols/tablet-v2.cpp:715:44: error: unknown type name 'wl_resource'
  715 | CCZwpTabletPadRingV2::CCZwpTabletPadRingV2(wl_resource* resource) {
      |                                            ^
protocols/tablet-v2.cpp:824:46: error: unknown type name 'wl_resource'
  824 | CCZwpTabletPadStripV2::CCZwpTabletPadStripV2(wl_resource* resource) {
      |                                              ^
protocols/tablet-v2.cpp:944:46: error: unknown type name 'wl_resource'
  944 | CCZwpTabletPadGroupV2::CCZwpTabletPadGroupV2(wl_resource* resource) {
      |                                              ^
protocols/tablet-v2.cpp:1012:80: error: unknown type name 'wl_resource'
 1012 | static void _CZwpTabletPadV2Enter(void* data, void* resource, uint32_t serial, wl_resource* tablet, wl_resource* surface) {
      |                                                                                ^
protocols/tablet-v2.cpp:1012:101: error: unknown type name 'wl_resource'
 1012 | static void _CZwpTabletPadV2Enter(void* data, void* resource, uint32_t serial, wl_resource* tablet, wl_resource* surface) {
      |                                                                                                     ^
protocols/tablet-v2.cpp:1018:80: error: unknown type name 'wl_resource'
 1018 | static void _CZwpTabletPadV2Leave(void* data, void* resource, uint32_t serial, wl_resource* surface) {
      |                                                                                ^
protocols/tablet-v2.cpp:1108:36: error: unknown type name 'wl_resource'
 1108 | CCZwpTabletPadV2::CCZwpTabletPadV2(wl_resource* resource) {
      |                                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

**Comment by jbeich** [comment]
Nevermind. I've accidentally failed to test hyprwayland-scanner 0.4.4 which isn't affected.

**Comment by vaxerski** [comment]
yah 0.4.3 had a vaxry moment
