### ISSUE TITLE
Cannot rebuild using hyprutils 0.4

### ISSUE THREAD

**Issue by alerque** [hyprwm/hyprpaper#235]
Previously this has been building fine using released versions of hypr*, but recently I bumped the hyprutils package in Arch Linux to 0.4 that this no longer cleanly rebuilds. Here is the new error:

```
[ 88%] Building CXX object CMakeFiles/hyprpaper.dir/protocols/fractional-scale-v1.cpp.o
[ 96%] Building CXX object CMakeFiles/hyprpaper.dir/protocols/tablet-v2.cpp.o
[ 96%] Building CXX object CMakeFiles/hyprpaper.dir/protocols/xdg-shell.cpp.o
/build/hyprpaper/src/hyprpaper-0.7.3/src/Hyprpaper.cpp: In lambda function:
/build/hyprpaper/src/hyprpaper-0.7.3/src/Hyprpaper.cpp:204:78: error: ‘wl_resource’ has not been declared
  204 |             m_pSeatPointer->setEnter([this](CCWlPointer* r, uint32_t serial, wl_resource* surface, wl_fixed_t x, wl_fixed_t y) {
      |                                                                              ^~~~~~~~~~~
/build/hyprpaper/src/hyprpaper-0.7.3/src/Hyprpaper.cpp:204:38: error: cannot convert ‘CHyprpaper::createSeat(Hyprutils::Memory::CSharedPointer<CCWlSeat>)::<lambda(CCWlSeat*, wl_seat_capability)>::<lambda(CCWlPointer*, uint32_t, int*, wl_fixed_t, wl_fixed_t)>’ to ‘std::function<void(CCWlPointer*, unsigned int, wl_proxy*, int, int)>’
  204 |             m_pSeatPointer->setEnter([this](CCWlPointer* r, uint32_t serial, wl_resource* surface, wl_fixed_t x, wl_fixed_t y) {
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      |
      |                                      CHyprpaper::createSeat(Hyprutils::Memory::CSharedPointer<CCWlSeat>)::<lambda(CCWlSeat*, wl_seat_capability)>::<lambda(CCWlPointer*, uint32_t, int*, wl_fixed_t, wl_fixed_t)>
  205 |                 if (!m_pCursorShape) {
      |                 ~~~~~~~~~~~~~~~~~~~~~~
  206 |                     m_pSeatPointer->sendSetCursor(serial, nullptr, 0, 0);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  207 |                     return;
      |                     ~~~~~~~
  208 |                 }
      |                 ~
  209 |
      |
  210 |                 m_pSeatCursorShapeDevice->sendSetShape(serial, wpCursorShapeDeviceV1Shape::WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_DEFAULT);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  211 |             });
      |             ~
In file included from /build/hyprpaper/src/hyprpaper-0.7.3/src/helpers/../render/LayerSurface.hpp:6,
                 from /build/hyprpaper/src/hyprpaper-0.7.3/src/helpers/Monitor.hpp:4,
                 from /build/hyprpaper/src/hyprpaper-0.7.3/src/Hyprpaper.hpp:6,
                 from /build/hyprpaper/src/hyprpaper-0.7.3/src/Hyprpaper.cpp:1:
/build/hyprpaper/src/hyprpaper-0.7.3/./protocols/wayland.hpp:1038:86: note:   initializing argument 1 of ‘void CCWlPointer::setEnter(std::function<void(CCWlPointer*, unsigned int, wl_proxy*, int, int)>)’
 1038 |     void setEnter(F<void(CCWlPointer*, uint32_t, wl_proxy*, wl_fixed_t, wl_fixed_t)> handler);
      |                                                                                      ^
make[2]: *** [CMakeFiles/hyprpaper.dir/build.make:135: CMakeFiles/hyprpaper.dir/src/Hyprpaper.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/build/hyprpaper/src/hyprpaper-0.7.3/src/ipc/Socket.cpp: In lambda function:
/build/hyprpaper/src/hyprpaper-0.7.3/src/ipc/Socket.cpp:77:26: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   77 |                     write(ACCEPTEDCONNECTION, m_szReply.c_str(), m_szReply.length());
      |                     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/hyprpaper.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by alerque** [comment]
@fufexan has pointed out in my comment on the Flake lockfile bump that this *is* buildable against hyprutils-0.4. It's possible that some other dependency version in Arch changed between builds, but I'm at a loss for what it is. The Hyprutils bump I just did was the obvious choice to blame.

**Comment by fufexan** [comment]
@alerque regarding your question in https://github.com/hyprwm/hyprpaper/commit/4d2e2b7f073fd69ace20b2d6b7a6eca93e5f6f18#r151680546 (and here). Have `hyprlang` and `hyprgraphics` had rebuilds triggered by `hyprutils-0.4`?

**Comment by alerque** [comment]
Yes, both hyprlang and hyprgraphics were rebuilt first against hyprutils-0.4 before trying the hyprpaper build that failed.

**Comment by fufexan** [comment]
I've cherry-picked my commit on top of the release tag, and it doesn't build for me either.
@vaxerski can we get a release?

**Comment by alerque** [comment]
Yes it looks like my error is directly related to 505e447 which is after the last release. So yes this needs a release to work with other current stable versions.

**Comment by vaxerski** [comment]
at your service https://github.com/hyprwm/hyprpaper/releases/tag/v0.7.4

**Comment by alerque** [comment]
Thanks. Arch Linux packages are all fresh again.

**Comment by vaxerski** [comment]
wonderful, thanks for updating!
